// This bundle is generated by the Vercel build command before the function
// is analyzed. Keeping this wrapper in JavaScript avoids Vercel compiling the
// workspace's Node16 TypeScript source tree.
let handlerPromise;

module.exports = async function handler(req, res) {
  handlerPromise ??= import("../vercel-handler.mjs").then(({ default: handler }) => handler);
  return handlerPromise.then((handler) => handler(req, res));
};