// This bundle is generated by the Vercel build command before the function
// is analyzed. Keeping this wrapper in JavaScript avoids Vercel compiling the
// workspace's Node16 TypeScript source tree.
export { default } from "../vercel-handler.mjs";